version: '3'

services:
  php:
    build: .
    volumes:
      - .:/var/www
    ports:
      - 18888:80
    container_name: php

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
        - 18889:3306
    environment:
        MYSQL_DATABASE: to_camp
        MYSQL_USER: user
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_PASSWORD: pass
    container_name: mysql

  mysql_test:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
        - 18890:3306
    environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: 'to_camp'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
