name: Run by push to feature branch

on:
  push:
    branches:
      - 'feature/*'

jobs:
  laravel-setup-and-lint-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: 'to_camp'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: PHP set up
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1.19
          tools: composer:v2.5.7
      #     extensions: 'mysql, mysqli, pdo_mysql'

      - run: php -v

      - name: Composer cache
        id: composer-cache
        run: echo "dir=$(composer config cache-file-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-key: ${{ runner.os }}-composer

      - name: Add permissions
        run: chmod -R 777 storage bootstrap/cache
        shell: bash

      - name: Composer install
        run: composer install -n --prefer-dist
        shell: bash

      - name: Set up npm
        run: |
          npm install
          npm run build
        shell: bash

      - name: Run code sniffer
        run: |
          ./vendor/bin/phpcs --standard=phpcs.xml ./
        shell: bash

      - name: Prepare testing
        run: |
          cp .env.example .env
          php artisan key:generate
        shell: bash

      - name: Run migration
        run: |
          php artisan migrate:refresh
        env:
          APP_ENV: 'testing'
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        shell: bash

      - name: Run phpunit
        run: |
          php artisan test
        env:
          APP_ENV: 'testing'
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        shell: bash
