name: Deploy to fly

on:
  push:
    branches:
      - 'feature/*'

jobs:
  deploy-to-fly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1.19
          tools: composer:v2.5.7
          extensions: 'mysql, mysqli, pdo_mysql'

      - name: Composer cache
        id: composer-cache
        run: echo "dir=$(composer config cache-file-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-key: ${{ runner.os }}-composer

      - name: Add permissions
        run: chmod -R 777 storage bootstrap/cache
        shell: bash

      - name: Composer install
        run: composer install -n --prefer-dist
        shell: bash

      - name: Set up npm
        run: |
          npm install
          npm run build
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        shell: bash
