name: Deploy to fly

on:
  push:
    branches:
      - 'feature/*'

jobs:
  deploy-to-fly:
    runs-on: ubuntu-latest
    steps:
      - run: cd ..
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        shell: bash
